version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/resultados

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alvarodelburgoperez
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
